homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

# Show links to resources in log and frontend
# introduction:

logger:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: secret

mqtt:
  broker: mosquitto

snips:

intent_script:
  GetTime:
    action:
      service: rest_command.espeak
      data_template:
        message: "It is {{ now().strftime('%I') | int }} {{ now().strftime('%M %p') }}."

rest_command:
  espeak:
    url: http://rhasspy:12101/api/text-to-speech?voice=en
    method: POST
    headers:
      content_type: text/plain
    payload: '{{ message }}'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
