homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:

lovelace:
  mode: yaml

http:
  api_password: secret

intent_script:
  GetTime:
    action:
      service: rest_command.espeak
      data_template:
        message: "It is {{ now().strftime('%I') | int }} {{ now().strftime('%M %p') }}."
  GetTemperature:
    action:
      service: rest_command.espeak
      data_template:
        message: "It is {{ states('sensor.temperature') }} degrees."
  GetGarageState:
    action:
      service: rest_command.espeak
      data_template:
        message: >
          {% if is_state('binary_sensor.garage_door', 'off') %}
            The garage door is closed.
          {% else %}
            The garage door is open.
          {% endif %}
  ChangeLightState:
    action:
      service_template: 'switch.turn_{{ state }}'
      data_template:
        entity_id: 'switch.{{ name | replace(" ", "_") }}'
  ChangeLightColor:
    action:
      service: mqtt.publish
      data_template:
        topic: 'bedroom_light/set'
        payload: 'on,255,255,0'

# Lights
switch:
  - platform: command_line
    switches:
      living_room_lamp:
        command_on: "echo 'Living room lamp ON'"
        command_off: "echo 'Living room lamp OFF'"
      garage_light:
        command_on:  "echo 'Garage light ON'"
        command_off: "echo 'Garage light OFF'"

# Doors
binary_sensor:
  - platform: command_line
    name: garage_door
    command: "bash -c 'sec=$(date +%s); [[ $(($sec % 2)) -eq 0 ]] && echo open || echo closed'"
    payload_on: "closed"
    payload_off: "open"
    
# Temperature
sensor:
  - platform: command_line
    name: temperature
    unit_of_measurement: "°C"
    command: "date +%S"

light:
  - platform: mqtt
    schema: template
    name: bedroom_light
    command_topic: "bedroom_light"
    command_on_template: "on"
    command_off_template: "off"
    state_topic: "bedroom_light/set"
    state_template: "{{ value.split(',')[0] }}"
    red_template: "{{ value.split(',')[1] }}"
    green_template: "{{ value.split(',')[2] }}"
    blue_template: "{{ value.split(',')[3] }}"

mqtt:
  broker: mosquitto

rest_command:
  espeak:
    url: http://rhasspy:12101/api/text-to-speech?voice=en
    method: POST
    headers:
      content_type: text/plain
    payload: '{{ message }}'

snips:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
