version: '2'
services:
  rhasspy:
    image: synesthesiam/rhasspy-server:latest
    environment:
      - RHASSPY_PROFILES=/profiles
    volumes:
      - $HOME/.rhasspy/profiles:/profiles
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "12101:12101"
    command: -d mqtt.enabled true -d mqtt.host mosquitto -s wake.system hermes
    depends_on:
      - snowboy
  snowboy:
    image: synesthesiam/snowboy:1.3.0
    volumes:
      - /run/dbus:/run/dbus
    command: --host mosquitto --model /models/okay_rhasspy.pmdl
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto
